version: "3.9"
services:
  app:
    build: .
    container_name: sse-app
    ports:
      - "8080:8080"   # app port (for debugging)
    environment:
      # these env names map to viper keys because of SetEnvKeyReplacer
      - REDIS_URL=redis:6379
      - SERVER_ADDR=:8080
    command: ["./sse-notifications", "server"]
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sse-net

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 5s
    container_name: sse-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - sse-net

  nginx:
    image: nginx:1.27-alpine
    container_name: sse-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - sse-net

networks:
  sse-net:
    driver: bridge
